spring.application.name=langchain4j_springboot

#ollama
langchain4j.ollama.chat-model.base-url=http://localhost:11434
langchain4j.ollama.chat-model.model-name=qwen3.5:9b
langchain4j.ollama.chat-model.temperature=0.7

langchain4j.ollama.streaming-chat-model.base-url=http://localhost:11434
langchain4j.ollama.streaming-chat-model.model-name=qwen3.5:9b
langchain4j.ollama.streaming-chat-model.temperature=0.7

langchain4j.ollama.embedding-model.base-url=http://localhost:11434
langchain4j.ollama.embedding-model.model-name=qwen3-embedding:8b
